local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  inflation_radius: 0.4
  obstacle_range: 3.0
  raytracce_range: 0.2
  
  obsevation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    marking: true
    clearing: true

  static_map: false
  update_frequency: 2.0
  publish_frequency: 10.0
  rolling_window: true
<<<<<<< HEAD:config/move_base/dtw_robot1/local_costmap_params.yaml
  width: 5.0
  height: 5.0
=======
  width: 2.0
  height: 2.0
>>>>>>> 275a617ee89e417b72d03cf8caee6c8f9738e1a1:config/move_base/local_costmap_params.yaml
  resolution: 0.05