TrajectoryPlannerROS:
  # max_vel_x: 1.0
  # min_vel_x: 0.05
  # max_vel_theta: 1.0
  # min_vel_theta: 
  # min_in_place_vel_theta: 0.005
  # acc_lim_theta: 0.2
  # acc_lim_x: 2.0
  # acc_lim_y: 2.5
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  meter_scoring: true
  holonomic_robot: false
  controller_frequency: 20.0