robot_base_frame: base_link

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [
  [0.450, 0.100],
  [0.450, -0.100],
  # [0.150, -0.180],
  [-0.150, -0.180],
  [-0.150, 0.180]
  # [0.150, 0.180]
]
# robot_radius: 0.6

observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: front_laser_link
  topic: scan
  data_type: LaserScan
  marking: true
  clearing: true
  inf_is_valid: true