robot_base_frame: base_link

obstacle_range: 3.0
raytrace_range: 0.2
robot_radius: 0.2

observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: front_laser_link
  topic: scan
  data_type: LaserScan
  marking: true
  clearing: true
  inf_is_valid: true