local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  inflation_radius: 0.4
  obstacle_range: 3.0
  raytracce_range: 0.2
  
  obsevation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    marking: true
    clearing: true

  static_map: false
  update_frequency: 2.0
  publish_frequency: 1.0
  rolling_window: true
  width: 1.0
  height: 1.0
  resolution: 0.05