local_costmap:
  global_frame: odom
  footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
  inflation_radius: 0.55
  obstacle_range: 3.0
  raytracce_range: 3.5
  
  obsevation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    marking: true
    clearing: true

  static_map: false
  update_frequency: 2.0
  publish_frequency: 1.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05